### ISSUE TITLE
Week 2 Reference Files : Box

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#1]
- Overview of Hills
- Week 2 Assignments

[]https://app.box.com/s/0d56tulvikzilbzixgfc1fg2h3c963yn

**Comment by akallish** [comment]
@omkarID @lmcclure1 @mgokani1201 please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by omkarID** [comment]
@akallish the box link shared doesn't contain any files.

**Comment by akallish** [comment]
> @akallish the box link shared doesn't contain any files.

@omkarID Try this : https://app.box.com/s/0d56tulvikzilbzixgfc1fg2h3c963yn

**Comment by omkarID** [comment]
@akallish this new lik works. thank you!

**Comment by akallish** [comment]
> @akallish this new lik works. thank you!

Anytime @omkarID

**Comment by lmcclure1** [comment]
@mgokani1201 @omkarID hey i started reading this

**Comment by mgokani1201** [comment]
@lmcclure1  @omkarID started reading these materials..

**Comment by mgokani1201** [comment]
@omkarID and @lmcclure1  I have finished reviewing these.

**Comment by lmcclure1** [comment]
@omkarID @mgokani1201 i've finished the assignments overview and am onto the hills doc

**Comment by omkarID** [comment]
@lmcclure1 and @mgokani1201, I'm done with reading these.

**Comment by lmcclure1** [comment]
@omkarID @mgokani1201 I've finished reading these

**Comment by mgokani1201** [comment]
moving this to done since all have finished it.

**Comment by akallish** [comment]
@mgokani1201 Congratulations, you are the first team to complete a task.
