### ISSUE TITLE
Week 03 : Review Online Written Content

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#10]
Please read these articles in their entirety - before doing the tasks

What are user stories? 
(http://bit.ly/2Gmw7Y6)
(http://bit.ly/2IQVdwl)
(http://bit.ly/2pDhEgx)

GitHub Issues
(http://bit.ly/2rjMACX)

Creating tasks in issues
(http://bit.ly/2HSHGGG)

Text Formatting
(http://bit.ly/2YceDov)

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 I'm done with these.

**Comment by lmcclure1** [comment]
@omkarID @mgokani1201 I've completed these readings. I'm a bit confused on the connection between sub-hills and issues. It didn't mention hills or subhills in any of these

**Comment by akallish** [comment]
> @omkarID @mgokani1201 I've completed these readings. I'm a bit confused on the connection between sub-hills and issues. It didn't mention hills or subhills in any of these

@lmcclure1 an issue in gut hub is the basic building block. It can be a task or a story. For our purpose an issue = a story

**Comment by mgokani1201** [comment]
@omkarID and @lmcclure1 I've completed these readings as well and moving them to done.
