### ISSUE TITLE
Week 03 : Review Videos

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#11]
Please watch these videos in their entirety - before doing the tasks 

GitHub Overviews
 (http://bit.ly/2Gedxhz)
 (http://bit.ly/2G8muwR)

GitHub & ZenHub 
(https://bit.ly/3qWfLZT)

How to write user stories 
(http://bit.ly/2IMDQwJ) 
(http://bit.ly/2I1gZMM)

**Comment by lmcclure1** [comment]
@mgokani1201 @omkarID I'm watching these videos before our meeting today as well.

**Comment by lmcclure1** [comment]
@mgokani1201 @omkarID I've watched all the short videos and skipped through the long one to read definitions of things

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 done reviewing these.

**Comment by mgokani1201** [comment]
@omkarID @lmcclure1 done reviewing these.
