### ISSUE TITLE
Week 03 : In Mural : Sub-Hills to epics to stories

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#12]
You can group related sub-hills together into an epic, or a body of work. An epic has an overarching name. Usually epics are associated with sprints as the related stories are worked on to create a unified deliverable. 

[Use the mural template to do this] (http://bit.ly/2MERVCI) 

Once you create epic names, you can then writer story statements based on key capabilities, features or workflow of your team’s solution. There is no minimum or maximum number of stories in an epic.

**Comment by mgokani1201** [comment]
@akallish do the sub hill groupings need to be mutually exclusive with respect to the sub hill they cluster?

**Comment by akallish** [comment]
> @akallish do the sub hill groupings need to be mutually exclusive with respect to the sub hill they cluster?

@mgokani1201 I am not sure of your question. In Mural you connected a sub hill to a what or a wow statement and then to specific words and to POEMS. For this week you are clustering sub-hills by similarities to what they are addressing like "Search" or "login" (examples) to create an associated body of work.

Does that make sense?

**Comment by mgokani1201** [comment]
> > @akallish do the sub hill groupings need to be mutually exclusive with respect to the sub hill they cluster?
> 
> @mgokani1201 I am not sure of your question. In Mural you connected a sub hill to a what or a wow statement and then to specific words and to POEMS. For this week you are clustering sub-hills by similarities to what they are addressing like "Search" or "login" (examples) to create an associated body of work.
> 
> Does that make sense?

I was meaning to ask: 
1)if every sub hill must appear in at least one epic? and 
2)if a sub hill can appear in one or more epic categories?

**Comment by omkarID** [comment]
- [x] @omkarID develop stories for Dev-ops/features epic before Wed, Feb 3 8am
- [x] @lmcclure1 develop stories for Content creation epic before Wed, Feb 3 8am
- [x] @mgokani1201 develop stories for search function epic before Wed, Feb 3 8am
- [x] @omkarID @lmcclure1 @mgokani1201 review each others stories before meeting on Wed, Feb 3 at noon.

**Comment by akallish** [comment]
> I was meaning to ask:

> 1)if every sub hill must appear in at least one epic? 
Answer : remember you are taking all your sub-hills and grouping them by commonality in theme and then naming an epic which defines a body of work, which then you will write your story statements for that epic.

> 2)if a sub hill can appear in one or more epic categories?
Answer : In the beginning of groupings, it is grouping sub-hills to an epic. Once you do that, if you think another epic could benefit from duplicating a sub-hill statement, why not!

**Comment by mgokani1201** [comment]
> > I was meaning to ask:
> 
> > 1)if every sub hill must appear in at least one epic?
> > Answer : remember you are taking all your sub-hills and grouping them by commonality in theme and then naming an epic which defines a body of work, which then you will write your story statements for that epic.
> 
> > 2)if a sub hill can appear in one or more epic categories?
> > Answer : In the beginning of groupings, it is grouping sub-hills to an epic. Once you do that, if you think another epic could benefit from duplicating a sub-hill statement, why not!

Great! thanks for clarifying that @akallish

**Comment by lmcclure1** [comment]
@mgokani1201 @omkarID I was inspired by group 2's mural and added in a color coded system to track the stories back to their sub-hills

**Comment by akallish** [comment]
> I was inspired by group 2's mural and added in a color coded system to track the stories back to their sub-hills

@mgokani1201 @omkarID @lmcclure1 Group 2's mural was an interesting diagram to connect specific sub-hills to specific stories. Group 1 is the farthest ahead in their use of tags, pins and iterations. Look at their repository and Kanban. 

I look forward to seeing today all of your stories transferred over and refinements to all story statements by tomorrow.

**Comment by mgokani1201** [comment]
@omkarID and @lmcclure1 moving this to done.
