### ISSUE TITLE
Week 03 : In GitHub : Transfer stories to GitHub

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#13]
- create two new tags : “story” and specific “(epic name)” tags
- create a new issues and give a story a name assign the team to the story
- select appropriate tags for story choose week three milestone state what part of the hill and what part of the sub-hill it is decomposed from
- draft the first iteration of the hill statement other team members then iterate and then @ reference others on the team  just like the hills/definitions/sub hills exercise, it is important to refine the language of the story

**Comment by mgokani1201** [comment]
- [x] @omkarID 
- [x] @lmcclure1 
- [x] @mgokani1201

**Comment by mgokani1201** [comment]
@akallish @omkarID @lmcclure1 can we use the check box system to indicate if we have each finished our assigned subtasks?  It is less invasive than everyone commenting "I am done"  and flooding notifications.... just a suggestion??

**Comment by akallish** [comment]
> can we use the check box system to indicate if we have each finished our assigned subtasks? It is less invasive than everyone commenting "I am done" and flooding notifications.... just a suggestion??

@mgokani1201 I believe that Jeff suggested this to make sure that an out of class issue that is in progress has clarity of who on the team got their part done. Your suggestion should be agreed to by the team. I am not going to weigh in on this topic.

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 Im done with these.

**Comment by lmcclure1** [comment]
@mgokani1201 @omkarID I have completed mine and will move this to done for all of us. I love Mrinali's suggestion of using the check box system instead of commenting "i am done". Let's discuss tonight during our reflection time and if we all agree, we can make this a standard moving forward.

**Comment by akallish** [comment]
@lmcclure1 using a check box with names is an excellent idea. I may add this to each out of class assignment.
