### ISSUE TITLE
Week 03 : Review Presentation

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#15]
Re-Review these FIRST
• Overview
• To Do

[Link to Box](https://app.box.com/s/nmxlf3h37xgurza8rlqv6au0et0da0e7)

**Comment by akallish** [comment]
I am sorry I forgot to add this out of class task to your kanban!

**Comment by mgokani1201** [comment]
> I am sorry I forgot to add this out of class task to your kanban!
No worries @akallish. Thanks!

**Comment by akallish** [comment]
> No worries @akallish. Thanks!

@mgokani1201 I am feeling very human right now . . .

**Comment by lmcclure1** [comment]
@omkarID @mgokani1201 I've completed reviewing this
