### ISSUE TITLE
Week 2 Homework : Read Online Articles

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#2]
- IBM Hills Overview : []https://ibm.co/2AfH2yA 
- Agile Terminology : []http://bit.ly/2uwt8Va

**Comment by akallish** [comment]
@omkarID @lmcclure1 @mgokani1201 please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by mgokani1201** [comment]
@omkarID and @lmcclure1 starting with these readings...

**Comment by lmcclure1** [comment]
I've completed these readings

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 done with reading these too.

**Comment by akallish** [comment]
I am happy that you are communicating with each other on the progress of the tasks

**Comment by mgokani1201** [comment]
@omkarID @lmcclure1 finished with these and since I am the last one moving this to the "done" pile
