### ISSUE TITLE
Week 2 Homework : Mural

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#3]
- Who are we as a team Mural
- Complete goals, hills, definitions & sub-hills (Example of hill definition : []http://bit.ly/2BSgO6p

Team 3 : []http://bit.ly/2XHs0g4

**Comment by akallish** [comment]
@omkarID @lmcclure1 @mgokani1201 please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by akallish** [comment]
![Screen Shot 2021-01-23 at 1 49 53 PM](https://user-images.githubusercontent.com/35602533/105612736-7631b480-5d83-11eb-88f2-2531fbb0614e.jpg)

@mgokani1201, @lmcclure1, @omkarID this should help you with your hills exercise

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 Movin this task to inprogress as we worked on the 'Who we are?' mural

**Comment by mgokani1201** [comment]
@lmcclure1 @omkarID  Are you guys able to see the Agile course workspace in your mural account? for some reason, i can't and always have to view as a visitor. @akallish  is this the way it is set up?

**Comment by akallish** [comment]
> @lmcclure1 @omkarID Are you guys able to see the Agile course workspace in your mural account? for some reason, i can't and always have to view as a visitor. @akallish is this the way it is set up?

@mgokani1201 Thanks for bringing this problem up. Went into Mural to fix room permissions. All of you can see each others names, can duplicate murals and invite visitors to see a mural. Good luck.

**Comment by lmcclure1** [comment]
@omkarID @mgokani1201 I've added a first draft of 9 sub-hills that relate to the UI/UX of the filters. I read through the info from Adrian and believe each of those lines would be a different sub-hill, addressing the development component.

**Comment by akallish** [comment]
> @omkarID @mgokani1201 I've added a first draft of 9 sub-hills that relate to the UI/UX of the filters. I read through the info from Adrian and believe each of those lines would be a different sub-hill, addressing the development component.

@lmcclure1 thanks for this message. To put this in context, a goal with three hills may have 300 or more sub-hill statements.

**Comment by akallish** [comment]
@omkarID @lmcclure1 @mgokani1201 

Good Morning! I reviewed your hills mural and it is shaping up nicely.

- the goal is ok. words like "selection", "relevant", "various", "maximize the potential" sound interesting but not sure if I read the goal, I get the value of AirBnB One
- hills : I think your hills are fantastic. Well done.
- definitions : ok. Additional Filters, Individual Preferences and Individual Requirements could be much more specific 
- in the sub-hills, they seem to be coming along, but would directly address and connect to hosts, guests and partners in some way
