### ISSUE TITLE
Week 2 Homework : GitHub

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#4]
Explore your GitHub repository. Go into each individual homework task and ask questions, have conversations in the task comment areas. Remember use "@" to refer to your team mates or you can put me in the stream by referring to my handle @akallish

Team 3 : IITIDIDX597/sp_2021_team3 : []https://bit.ly/35GvXWC

**Comment by akallish** [comment]
@omkarID @lmcclure1 @mgokani1201 please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by mgokani1201** [comment]
@lmcclure1 @mgokani1201 Are you guys able to see the Agile course workspace in your mural account? for some reason, i can't and always have to view as a visitor. @akallish is this the way it is set up?
