### ISSUE TITLE
Week 4 : Virtual visit from CDK Global

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#40]
Review out of class PDF files (3)

[Link to download] (http://bit.ly/3jgFSbb)

- [x] Mrinali Gokani
- [x] Lana McClure
- [x] Omkar Todkar

**Comment by omkarID** [comment]
@akallish both the **CDK Website** and **SAFe Overview** short URLs on slide 6 of the deck [IDX_597_Week4_CDKGlobal.pdf](https://app.box.com/s/tpc0ksu7xdv98ohdwgf2zuixuc9sfaza/file/772311586202) go to this [page](https://madeintandem.com/blog/goruco-2017-trust-teams/)

A quick google search led me to [CDK Global's site](https://www.cdkglobal.com/us)
Can you confirm if the Tandem link for SAFe overview is correct?

**Comment by akallish** [comment]
Hey @omkarID 

Use the links in the issue #42
