### ISSUE TITLE
Week 7 : Schedule mandatory 60 minute dry run of team presentation the week between March 04 and March 11

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#44]
Criteria and preparation suggestions for final presentations between March 04 and March 09 for one hour (dry run + critique).

[Link to download] (http://bit.ly/3jkM1Do)

- [x] Mrinali Gokani
- [x] Lana McClure
- [x] Omkar Todkar

**Comment by lmcclure1** [comment]
@akallish  is the dry run of the presentation scheduled with you or is it part of our synchronous time as a team the week of march 4-11?

**Comment by akallish** [comment]
> is the dry run of the presentation scheduled with you or is it part of our synchronous time as a team the week of march 4-11?

@lmcclure1 it is outside of our class time so it would need to be scheduled.

**Comment by mgokani1201** [comment]
@akallish follow up for dry run times:
- [ ] Fri 3/5 : 5-6pm CST
- [ ]  Sun 3/7 : 8-11am CST
- [x]  Mon 3/8: 12-1pm CST

**Comment by akallish** [comment]
> @akallish follow up for dry run times:
> 
> - [ ] Fri 3/5 : 5-6pm CST
> 
> - [ ]  Sun 3/7 : 8-11am CST
> 
> - [x]  Mon 3/8: 12-1pm CST

@mgokani1201 i look forward to the Monday dry run. Send a zoom or other link

**Comment by mgokani1201** [comment]
@akallish Thank you for your prompt response. 
You should have received a zoom link from @lmcclure1 already. 
See you then!

**Comment by akallish** [comment]
@mgokani1201 i did indeed get an invitation and promptly accepted it. Looking forward to hearing the team story.
