### ISSUE TITLE
Prep for Demo

### ISSUE THREAD

**Issue by mgokani1201** [IITIDIDX597/sp_2021_team3#45]
- [x] @lmcclure1 collect and link all materials to master mural (https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1612717616751/e6efcbccbc4ba6d030eadec06f8196467e07befd)
- [x] @mgokani1201 creating demo issues
- [x] @omkarID create a demo of the presentation (backup) plan

**Comment by akallish** [comment]
@mgokani1201 looks like a mobilization
