### ISSUE TITLE
Revise agile terminology

### ISSUE THREAD

**Issue by mgokani1201** [IITIDIDX597/sp_2021_team3#46]
Agile Terminology : []http://bit.ly/2uwt8Va

- [x] @lmcclure1 
- [x] @omkarID 
- [x] @mgokani1201

**Comment by lmcclure1** [comment]
@mgokani1201 @omkarID I'm reviewing the agile terms by hand-writing each term, the definition in my own words and a tangible example. I've gotten through the people section. I probably won't complete this task until next week bc it's rather time consuming, but it's been a very helpful method

**Comment by akallish** [comment]
@lmcclure1 interesting method and now you have my curiosity
