### ISSUE TITLE
Week 2 Homework : Update team Task Board in ZenHub 

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#5]
Remember to move each task across the Kanban from the New Issues pipeline, across to done.

Team 3 : []http://bit.ly/3nOvCaB

**Comment by akallish** [comment]
@omkarID @lmcclure1 @mgokani1201 please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by mgokani1201** [comment]
@akallish our team has started working on this...

**Comment by akallish** [comment]
Thank you @mgokani1201 fod the message and good luck with your tasks
