### ISSUE TITLE
Week 5 Out of Class Work : Create acceptance criteria for five stories

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#56]
- [ ] Mrinali Gokani
- [ ] Lana McClure
- [ ] Omkar Todkar 

- THREE ITERATIONS of acceptance criteria for each story is required.
- Tag the five stories as "Acceptance Criteria"

**Comment by mgokani1201** [comment]
- [x] Iteration 1
- [x] Iteration 2
- [ ] Iteration 3

**Comment by lmcclure1** [comment]
@omkarID @mgokani1201 I changed the milestone on our five stories to "week 5: acceptance criteria" 

- [x] iteration 1 

- [x] iteration 2

- [ ] iteration 3
