### ISSUE TITLE
Week 6 : Out of Class Box Directory Overview, Assignment PDFs

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#59]
[Link to download two files] (http://bit.ly/2Pg81Er)

**Comment by lmcclure1** [comment]
- [x] @mgokani1201 

- [x] @omkarID 

- [x] @lmcclure1

**Comment by akallish** [comment]
@lmcclure1 @mgokani1201 @omkarID I apologize for not putting the checklists in all the out of class work items. My bad . . .
