### ISSUE TITLE
Week 6 Out of Class Work : Mural Team Sizing

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team3#62]
Each team has a preformatted Mural t-shirt sizing in their team mural area
[Team 03 ] (http://bit.ly/3aWlyJB)

Size the five stories that have acceptance criteria and order all the stories in your team backlog.
Remember each story is sized relative to the previous stories that are sized. So be prepared to move earlier stories around from S to M to L

Then in GitHub :
• tag each of the five stories as small, medium or large
• tag all stories in backlog as hot, warm, cool, or icebox

Example of a completed one : [http://bit.ly/2VWDw4M](http://bit.ly/2VWDw4M)

**Comment by lmcclure1** [comment]
@akallish we are on a sync mtg right now and discussing the temperature check and came to this question: is the release after hot and warm stories are complete or is it after the cool? or do we define this as a team?

**Comment by akallish** [comment]
@lmcclure1 you should define this as a team. That will determine what is important to do first, second, etc.
