### ISSUE TITLE
Demo Set up Async tasks

### ISSUE THREAD

**Issue by mgokani1201** [IITIDIDX597/sp_2021_team3#66]
- [x] decomposition mural - fine tune @omkarID 
- [x] learning murals - @lmcclure1 
- [x] re check mural links - @mgokani1201 
- [x] Feedback set up issue - @mgokani1201  (do it live)
- [x] Drop photos in team mural
- [x] get airbnb one logo

**Comment by akallish** [comment]
@mgokani1201 interesting use of an issue as a checklist

**Comment by mgokani1201** [comment]
@omkarID and @lmcclure1 I was thinking let's use a collective team photo instead of individual ones
