### ISSUE TITLE
Presentation feedback

### ISSUE THREAD

**Issue by mgokani1201** [IITIDIDX597/sp_2021_team3#69]
**Things that went well:**
- [ ] point 1
- [ ] point 2

**Things that need to be worked on:**
- [ ] point 1
- [ ] point 2

**Comment by mgokani1201** [comment]
**V1 feedback from adam**

was good:
- [ ] timing and style of explaining 
- [ ] good at the explanation of individual parts (power of 3s)
- [ ] good use. of filters, labels, and use GH/ZH

to Improve:
- [ ] use filter presentation / backlog
- [ ] use DECOMPOSE word and TRACEABILITY - continuous thing to ensure things are aligned
- [ ] use original hills murals to show zoom > then shift to clean up  version
- [ ] used poems to define sub hill
- [ ] intentional zooming in-out and across 
- [ ] selected 5 out of 20 but will talk through only 1-2 for time (. keep refined multiple versions)
- [x] talk about 2 in sizing aspect
- [ ] learning mural talk about instrumented platforms (sync & async) - get work done but also feel more in control
- [ ] imp of real-time comments from adam, cross-team chat.
- [ ] AGILE TERMS - concepts explained but terms need work

**Comment by akallish** [comment]
@mgokani1201 Good summation. Overall, the presentation was good. Now let's get it to very good!
