### ISSUE TITLE
Upload past projects and review others

### ISSUE THREAD

**Issue by lmcclure1** [IITIDIDX597/sp_2021_team3#7]
upload here: https://app.box.com/folder/130243103988

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 moving this over to in progress as I have started uploading files to our shared Box folder\\https://app.box.com/s/zd1ynjm5djwg213wn5zocr4dtcy5u1aa

**Comment by mgokani1201** [comment]
started working on this one

**Comment by mgokani1201** [comment]
I have finished this one.

**Comment by lmcclure1** [comment]
I've uploaded mine and will review all shortly

**Comment by omkarID** [comment]
@mgokani1201 the GuideID site link seems to be broken. Also, can you give us access to the Miro board. Thanks!

**Comment by akallish** [comment]
@omkarID here is the link to GuideID : []https://sites.google.com/id.iit.edu/id-student-resources/home?pli=1&authuser=2

**Comment by omkarID** [comment]
Thanks @akallish!

**Comment by akallish** [comment]
@omkarID @lmcclure1 @mgokani1201 You are the first team to open up a new issue. Congratulations.

**Comment by mgokani1201** [comment]
> @mgokani1201 the GuideID site link seems to be broken. Also, can you give us access to the Miro board. Thanks!

@omkarID and @lmcclure1 try this for the miro access to my Guide ID project : https://miro.com/app/board/o9J_lXCPK1M=/
have given the view access as well.

**Comment by akallish** [comment]
@mgokani1201 @omkarID @lmcclure1 i saw the comments about Miro. While it does the same thing as Mural, I would like us to use Mural to avoid asset sprawl. Thanks.

**Comment by mgokani1201** [comment]
> > @mgokani1201 the GuideID site link seems to be broken. Also, can you give us access to the Miro board. Thanks!
> 
> @omkarID and @lmcclure1 try this for the miro access to my Guide ID project : https://miro.com/app/board/o9J_lXCPK1M=/
> have given the view access as well.
 also, the guide ID site can only be used if you are using the ID email address (id.iit.edu)
find the link below: https://sites.google.com/id.iit.edu/id-student-resources/home?authuser=0

**Comment by mgokani1201** [comment]
> @mgokani1201 @omkarID @lmcclure1 i saw the comments about Miro. While it does the same thing as Mural, I would like us to use Mural to avoid asset sprawl. Thanks.

@akallish that is just to view an older project. Our team is using Mural for this class.

**Comment by akallish** [comment]
> that is just to view an older project. Our team is using Mural for this class.

Hey @mgokani1201 thanks for the clarification!
