### ISSUE TITLE
Week 2: Asynchronously meet with individual contact to get technical info required for subhills and add to Mural

### ISSUE THREAD

**Issue by omkarID** [IITIDIDX597/sp_2021_team3#9]
Team 3 members to meet with their respective contact to get technical info required to define sub hill and and collect it in the  'Ideas and Thoughts Dump' mural board before meeting on Wednesday morning at 11am

https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1611528857420/03c5ac0143edc102c593486fd8c5feeb33020693

**Comment by omkarID** [comment]
Hey @lmcclure1 @mgokani1201 , I had a chance to speak to my Friend Adrian about the sub hills and he was very helpful. Added summarized discussion notes in Mural.

**Comment by akallish** [comment]
> Hey @lmcclure1 @mgokani1201 , I had a chance to speak to my Friend Adrian about the sub hills and he was very helpful. Added summarized discussion notes in Mural. 

@omkarID which mural with Adrian notes?

**Comment by lmcclure1** [comment]
@omkarID @mgokani1201 my contacts haven't responded yet, but I did locate the prototypes. I'll upload them to the past projects folder

**Comment by omkarID** [comment]
> > Hey @lmcclure1 @mgokani1201 , I had a chance to speak to my Friend Adrian about the sub hills and he was very helpful. Added summarized discussion notes in Mural.
> 
> @omkarID which mural with Adrian notes?


Hey @akallish We created a new mural to dump our idea/thought/notes which I added in the thread above. here it is again:
https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1611528857420/03c5ac0143edc102c593486fd8c5feeb33020693

Please let me know if you cannot access it.

**Comment by akallish** [comment]
> Team 3 members to meet with their respective contact to get technical info required to define sub hill and and collect it in the  'Ideas and Thoughts Dump' mural board before meeting on Wednesday morning at 11am
> 
> 
> 
> https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1611528857420/03c5ac0143edc102c593486fd8c5feeb33020693

@omkarID thanks for the clarification. Yes I saw this and am glad the team created this mural to refine the goal statement.

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 moving this over to Done as we met and discussed the sub hills earlier today.
